# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  AxeleraExport:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: yolo26n
            data: coco8.yaml
          - model: yolo26n-pose
            data: coco8-pose.yaml
          - model: yolo26n-cls
            data: imagenet10
          - model: yolo26n-obb
            data: dota8.yaml
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          activate-environment: true
      - name: Install requirements
        run: uv pip install -e ".[export]" --extra-index-url https://download.pytorch.org/whl/cpu --index-strategy unsafe-best-match
      - name: Run Axelera export
        run: yolo export model=${{ matrix.model }}.pt format=axelera data=${{ matrix.data }}
