# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  SonyIMXExport:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: yolo11n.pt
            data: coco8.yaml
          - model: yolo11n-seg.pt
            data: coco8-seg.yaml
          - model: yolo11n-pose.pt
            data: coco8-pose.yaml
          - model: yolo11n-cls.pt
            data: imagenet10
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          activate-environment: true
      - name: Install requirements
        run: uv pip install -e ".[export]" --extra-index-url https://download.pytorch.org/whl/cpu --index-strategy unsafe-best-match
      - name: Run Sony IMX export
        run: yolo export model=${{ matrix.model }} format=imx data=${{ matrix.data }}
